### ISSUE TITLE
TMO-G4AR Arcadyn encounters login error in Android, macOS

### ISSUE THREAD

**Issue by pigs-on-the-wing** [zacharee/ArcadyanKVD21Control#51] opened 2024-07-03 22:57 UTC
Login 401 errors encountered on both Android and macOS with latest HINT (build Version 35) on TMO-G4AR gateway
Screenshots enclosed

Android 13:
![Screenshot_20240703_155144_HINT_Control_708245264312290](https://github.com/zacharee/ArcadyanKVD21Control/assets/174661188/e9006890-7eea-4dcd-8d10-d13f00da763c)

macOS Sonoma 14.5 (23F79):
<img width="912" alt="Screenshot 2024-07-03 at 3 45 01 PM" src="https://github.com/zacharee/ArcadyanKVD21Control/assets/174661188/9fa9bc71-c6dd-49bd-b8e0-2f2b2e2513e4">

**Comment by zacharee** [comment] 2024-07-14 18:34
Duplicate of #2

**Closed by zacharee** 2024-07-14 18:34 UTC

**Comment by pigs-on-the-wing** [comment] 2024-07-15 17:58
Issue still exists in latest Android build 1.11.1 (downloaded, installed and tested on Jul 15, 2024)
See screenshots. Happy to help debug the issue

![Screenshot_20240715_105149_HINT_Control_1038621398077136](https://github.com/user-attachments/assets/d044fd1a-6e01-4c4e-83da-ce4016d43f08)
![Screenshot_20240715_105116_Settings_1038621567964598](https://github.com/user-attachments/assets/5b384068-f791-48b3-bc79-6d8b1dcc6a14)
