### ISSUE TITLE
Add an App Intent for the Reboot function to connect with Automations in the Shortcuts App

### ISSUE THREAD

**Issue by logicito** [zacharee/ArcadyanKVD21Control#62] opened 2024-07-22 17:04 UTC
The App is great, specially the latest TestFlight with colors, thank you.

Would it be possible to expose App functionality via App Intent, specifically the Reboot function, so I can create an automation in the Shortcuts app to schedule reboots on a weekly basis, for example.

**Comment by zacharee** [comment] 2024-07-23 22:02
Duplicate of #56

**Closed by zacharee** 2024-07-23 22:02 UTC
