### ISSUE TITLE
Arcadyan KVD21 throwing error "WiFi driver is busy. Please try again later."

### ISSUE THREAD

**Issue by natemccurdy** [zacharee/ArcadyanKVD21Control#49] opened 2024-06-09 02:23 UTC
HINT Control 1.10.5
OS: MacOS Intel
Gateway:
* Arcadyan KVD21
* Firmware: 1.00.22
* Hardware version: R01

When changing any Wifi setting on my KVD21, for example setting the 2.4 GHz channel to `11`, after clicking Save, the following error is thrown:

```
Request Timeout
{status==408
headers==[content-length=[132],content-type=[application/json],date=[Sun, 09 Jun 2024 02:00:33 GMT],server=[lighttpd/1.4.69]]
requestHeaders==[User-Agent=[homeisp/android/2.12.1],Authorization=[Bearer <redacted>],Accept=[application/json],Accept-Charset=[UTF-8]]
requestBody==
requestUrl==http://192.168.12.1/TMI/v1/network/configuration/v2?get=ap
requestMethod==GET}
{
  "result": {
    "error": "SetFailed",
    "message": "WiFi driver is busy. Please try again later.",
    "statusCode": 408
  }
}
```

In the meantime, I'm able to write new configs to the gateway with `curl` via https://gist.github.com/natemccurdy/03e9e3a8c692d010858add721a32d01c#file-write-gw-config-sh

**Comment by zacharee** [comment] 2024-07-14 18:48
Duplicate of #44

**Closed by zacharee** 2024-07-14 18:48 UTC
