### ISSUE TITLE
Cannot login/authenticate

### ISSUE THREAD

**Issue by pilmoore** [zacharee/ArcadyanKVD21Control#39] opened 2024-03-03 19:10 UTC
![IMG_0065](https://github.com/zacharee/ArcadyanKVD21Control/assets/162051846/7b50adf0-2ce8-4f82-aefb-b5b4caaed07d)

I cannot login using lPhone, iPad or pc. 
I have the Arcadyan TMOG4AR with an Linksys mesh network. When attempting a login I reference the Arcadyan ip 192.168.12.1. I have tried the Linksys, 192.168.1.1, with same results.

Hint Control worked when initially installed on my iPhone.  I logged out after 2-3 days and when I decided to login again I started getting the error.I then installed on my iPad and pc and received the same message.

The router password was changed on the T-Mobile gateway using only upper and lower case letters, no special characters or numbers. I have also tried the original router password.

Any help or thoughts will be appreciated.
Larry Moore

**Comment by gambit820** [comment] 2024-03-05 19:09
Getting the same issue on IOS and Mac aarch64

Unauthorized
{status==401
headers==[content-length=[147],content-type=[application/json],date=[Tue, 05 Mar 2024 19:07:15 GMT],server=[lighttpd/1.4.69]]
requestHeaders==[Accept=[application/json],Accept-Charset=[UTF-8]]
requestBody=={"username":"admin","password":"***"}
requestUrl==http://192.168.12.1/TMI/v1/auth/login
requestMethod==POST}
{
  "result": {
    "error": "AuthorizationError",
    "message": "Not Authorized, Access token is missing or invalid",
    "statusCode": 401

**Comment by gambit820** [comment] 2024-03-15 10:19
I was able to finally get in, if you changed the wifi password try using that to log in with.

**Comment by zacharee** [comment] 2024-04-06 23:30
Duplicate of https://github.com/zacharee/ArcadyanKVD21Control/issues/2

**Closed by zacharee** 2024-04-06 23:30 UTC
